// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/gserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_gserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_gserver_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_gserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_gserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_gserver_proto protoreflect.FileDescriptor

const file_proto_gserver_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gserver.proto\x12\agserver\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x1f\n" +
	"\vGetResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2=\n" +
	"\tShortener\x120\n" +
	"\x03Get\x12\x13.gserver.GetRequest\x1a\x14.gserver.GetResponseB\x0fZ\rgserver/protob\x06proto3"

var (
	file_proto_gserver_proto_rawDescOnce sync.Once
	file_proto_gserver_proto_rawDescData []byte
)

func file_proto_gserver_proto_rawDescGZIP() []byte {
	file_proto_gserver_proto_rawDescOnce.Do(func() {
		file_proto_gserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gserver_proto_rawDesc), len(file_proto_gserver_proto_rawDesc)))
	})
	return file_proto_gserver_proto_rawDescData
}

var file_proto_gserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gserver_proto_goTypes = []any{
	(*GetRequest)(nil),  // 0: gserver.GetRequest
	(*GetResponse)(nil), // 1: gserver.GetResponse
}
var file_proto_gserver_proto_depIdxs = []int32{
	0, // 0: gserver.Shortener.Get:input_type -> gserver.GetRequest
	1, // 1: gserver.Shortener.Get:output_type -> gserver.GetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gserver_proto_init() }
func file_proto_gserver_proto_init() {
	if File_proto_gserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gserver_proto_rawDesc), len(file_proto_gserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gserver_proto_goTypes,
		DependencyIndexes: file_proto_gserver_proto_depIdxs,
		MessageInfos:      file_proto_gserver_proto_msgTypes,
	}.Build()
	File_proto_gserver_proto = out.File
	file_proto_gserver_proto_goTypes = nil
	file_proto_gserver_proto_depIdxs = nil
}
