POST http://localhost:8080
Content-Type: text/plain

https://rbc.ru

###
GET http://localhost:8080/1806126526
Content-Type: text/plain

###
GET http://localhost:8080/1806126526
Content-Type: text/html

###
POST http://localhost:8080/api/shorten
Content-Type: application/json

{"url":"https://rbc.ru"}

###
GET http://localhost:8080/ping
Content-Type: text/plain

###
POST http://localhost:8080/api/shorten/batch
Content-Type: application/json

[{"correlation_id":"1","original_url":"https://rbc.ru"},{"correlation_id":"2","original_url":"https://ya.ru"}]
